name: go-demo-action

on:
    push:
        branches:
            - master

jobs:
    run_test:
        name: run-test
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: setup
              uses:  actions/setup-go@v5.0.1
            
            - name: run-test
              run: go test ./...
            
    build_and_save_docker_image:
        name : Build and save docker image 
        runs-on: ubuntu-latest
        needs: run_test

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2   

            - name: Setup docker build 
              uses: docker/setup-buildx-action@v1  

            - name: Build docker image
              run: |
                docker buildx build --platform linux/amd64,linux/arm64 -t madhumnnit/brockerimg:latest . 
                docker save -o brockerimg.tar madhumnnit/brockerimg:latest 
            - name : Uploading docker image as artifact in brocker repository
              uses: actions/upload-artifact@v2
              with:
                name : brockerimg 
                path : brockerimg.tar      


